### ISSUE TITLE
Error plotting genes

### ISSUE THREAD

**Issue by GabrielHoffman** [mcneney/LDheatmap#1]
I get an error when I run:

```
library(LDheatmap)
library(GenomicRanges)
query = GRanges("chr20", IRanges(61565666, 62643839))
plotGenes(start(query), end(query), seqnames(query),
        genome="hg38", plot_lines_distance = 0.04, splice_variants=TRUE, non_coding=TRUE)
```

 I get the error: 
```
Error in rgb(r, g, b, maxColorValue = 225) :
  color intensity 1.13333, not in [0,1] 
```

I think I found the source of the error:
 line 251 of plotGenes.R:
` gene_color <- rgb(r,g,b, maxColorValue = 225)`
should be
`gene_color <- rgb(r,g,b, maxColorValue = 255)`

**Comment by mcneney** [comment]
Dear Gabriel,

Thanks very much for your bug report and detailed fix, which we'll apply ASAP.

Brad

________________________________________
