### ISSUE TITLE
passing a matrix filled in the lower right triangle

### ISSUE THREAD

**Issue by mpage21** [mcneney/LDheatmap#10]
Hi @mcneney ,

I was wondering if a parameter could be added that would instruct LDheatmap on which part of the matrix to look at for creating the heatmap. Plink gives the option of printing the LD measurements to a square where the lower right triangle of the matrix is filled with values while the upper left matrix is filled with 0. It would be wonderful if I could use that matrix instead of needing to generate the full matrix. 

thank you!
Maddy

**Comment by mcneney** [comment]
LDheatmap uses the upper-triangular part of the matrix, so I think transposing your Plink output before passing to LDheatmap should work.

**Comment by mpage21** [comment]
Thank you for your quick response, I will try that. Additionally, is there a recommended max size for these heatmaps? We are looking at generating one for whole chromosomes, but is that feasible with LDheatmap?

**Comment by mcneney** [comment]
No max size that I know of. You might want to set a limit to the "depth" of LD (distance between markers) that you include on your heatmap though. The bioconductor snpStats package has a vignette on LD that might give useful guidance:  https://bioconductor.org/packages/devel/bioc/vignettes/snpStats/inst/doc/ld-vignette.pdf
