### ISSUE TITLE
Cannot install the LDheatmap in R version 4.2.3 

### ISSUE THREAD

**Issue by anne-ds-ai** [mcneney/LDheatmap#12]
Greetings!

I am using the R version 4.2.3 (2023-03-15). After typing the `install.packages("LDheatmap")`, my console outputs the error: 
Warning in install.packages :
  package ‘LDheatmap’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages.

How to address that?

**Comment by mcneney** [comment]
Hi Anni,

Sorry, LDheatmap is currently not on CRAN. We're working to get it back on. In the meantime you can install devtools and install from github with

`devtools::install_github("https://github.com/SFUStatgen/LDheatmap")`

**Comment by anne-ds-ai** [comment]
> Hi Anni,
> 
> Sorry, LDheatmap is currently not on CRAN. We're working to get it back on. In the meantime you can install devtools and install from github with
> 
> `devtools::install_github("https://github.com/SFUStatgen/LDheatmap")`

Thanks. That helps.

**Comment by 98fu** [comment]
hy i cannot install LDheatmap in R version 4.2.3 and with your given link also, I encountered error. 
arning message:
In Sys.setlocale("LC_ALL", "NO_NB.utf8") :
  OS reports request to set locale to "NO_NB.utf8" cannot be honored
Error: could not find function "install.packages"
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/v8/vmtxys7s59x30rwpr15njg2w0000gn/T//Rtmp0wJkOZ/filec1f7b6b1455/LDheatmap_1.0-5.tar.gz’ had non-zero exit status. Please help me solving this

**Comment by mcneney** [comment]
Hi, Can you confirm that the command you tried was `devtools::install_github("https://github.com/SFUStatgen/LDheatmap")` and that you have the `devtools` package installed? Thanks
