### ISSUE TITLE
Cannot Download LDheatmap

### ISSUE THREAD

**Issue by Tannervanorden** [mcneney/LDheatmap#13]
I cannot download LDheatmap using cran or devtools::install_github("SFUStatgen/LDheatmap"). Both say install failed. What do I do?

**Comment by mcneney** [comment]
Hi,

Can you please show me the complete error messages? Thanks,

Brad

On Nov 13, 2023, at 1:57 PM, Tannervanorden ***@***.***> wrote:

﻿

I cannot download LDheatmap using cran or devtools::install_github("SFUStatgen/LDheatmap"). Both say install failed. What do I do?
