### ISSUE TITLE
Cannot install the LDheatmap in R

### ISSUE THREAD

**Issue by LW-Zheng** [mcneney/LDheatmap#14]
typing the devtools::install_github("https://github.com/SFUStatgen/LDheatmap")("LDheatmap"), my console outputs the error:
Warning in install.packages :Error: Failed to install 'unknown package' from GitHub:Timeout was reached: [api.github.com] Resolving timed out after 10000 milliseconds

**Comment by mcneney** [comment]
Thanks for your interest in LDheatmap. I think you have a typo in the command with the extra ("LDheatmap") at the end, but that may just be from cutting and pasting into github. Can you confirm that you typed 

devtools::install_github("https://github.com/SFUStatgen/LDheatmap")

Brad

**Comment by LW-Zheng** [comment]
Thank you for your response. I have tried it again, and confirm that you typed devtools::install_github("https://github.com/SFUStatgen/LDheatmap").







Looking forward to hear from you.




Liwei Zheng

At 2024-05-08 00:32:43, "Brad McNeney" ***@***.***> wrote:

Thanks for your interest in LDheatmap. I think you have a typo in the command with the extra ("LDheatmap") at the end, but that may just be from cutting and pasting into github. Can you confirm that you typed

devtools::install_github("https://github.com/SFUStatgen/LDheatmap")

Brad
