### ISSUE TITLE
Cannot add Gene track with "LDheatmap.addGenes"

### ISSUE THREAD

**Issue by JPingAMMS** [mcneney/LDheatmap#2]
run example code, like:

```r
data(GIMAP5.CEU)
ll<-LDheatmap(GIMAP5.CEU$snp.data,GIMAP5.CEU$snp.support$Position,flip=TRUE)
llplusgenes <- LDheatmap.addGenes(ll, chr="chr7", genome="hg18")
```

got error: "Error: Bad Request"

Questions may be induced by interaction with "rtracklayer" package?

Will you please to check it?

**Comment by mcneney** [comment]
Thanks for your interest in LDheatmap. The example works for me. Do you have rtracklayer installed from BioConductor? Can you check by running the following code

> session <- rtracklayer::browserSession()
> GenomeInfoDb::genome(session) <- "hg18"

Thanks,
Brad

**Comment by JPingAMMS** [comment]
Hi, Brad, 
I tried your code, and no error happened.
Then, I google the error and found that it is firewall.
Please close it.

Thanks,
Jie
