### ISSUE TITLE
Impossible R Version Requirement

### ISSUE THREAD

**Issue by ManjotVirdee** [mcneney/LDheatmap#3]
In your most resent commit you changed the R dependency 
`- Depends: R (>= 2.14.0) `
`+ Depends: R (>= 4.1)`

The current version of R is 4.0.2 which makes it quite hard to install
`ERROR: this R is version 4.0.2, package 'LDheatmap' requires R >= 4.1`

`Depends: R (>= 4.0.1)` is a more reasonable requirement

**Comment by mcneney** [comment]
Sorry. This is in response to changes to the grid package for R version 4.1. I was told by CRAN to update LDheatmap and set the dependency to 4.1. You may have to use an old version from the archives at 
https://cran.r-project.org/src/contrib/Archive/LDheatmap/
until all this gets sorted out.

**Comment by mcneney** [comment]
OK, I've reconsidered. I've set the depends to 4.0.1 for the version on github as you suggested. I'll make local changes to 4.1 when submitting versions to cran.
