### ISSUE TITLE
Plot not shown when running LDheatmap

### ISSUE THREAD

**Issue by huw143** [mcneney/LDheatmap#5]
![Rplot](https://user-images.githubusercontent.com/64991387/199045185-48ab3edf-02db-4283-809a-25986881f7e8.jpeg)

Hello, 

Just let you know when I ran the function "LDheatmap", only this plot did not shown up, while other plots were Okay.

Please let me know how to solve this?

Best regards,

Hu

**Comment by gloriayxf** [comment]
Hi Hu,

Could you please share a short R Markdown document which reproduces the problem for you?

Best,
Gloria
