### ISSUE TITLE
CRAN? 

### ISSUE THREAD

**Issue by jpiaskowski** [mcneney/LDheatmap#7]
Hello,

Do you intend to put this package back on CRAN? 

Thank you.

**Comment by mcneney** [comment]
Yes, we need to fix some of the C source code, and will resubmit after that. Unfortunately no ETA. Do you need a compiled version?

**Comment by jpiaskowski** [comment]
No, it's a dependency for another package I'm working on, so just trying to figure out how to manage that. thank you for your work!
