### ISSUE TITLE
heatmap printed LD measurements on each cell -- too small to read

### ISSUE THREAD

**Issue by mpage21** [mcneney/LDheatmap#9]
Hello @mcneney,

Thank you for your work on this tool. I wanted to add the LD measurements to the cells, but they are currently too small to read (see attached picture). Is there a way to increase the text size? Here is the R command that I ran to generate the image. 

```
LDheatmap(test_matrix, color = rgb.palette(18), text=TRUE)
```
![Screenshot 2023-03-06 105815](https://user-images.githubusercontent.com/23090557/223164682-efacc6e8-9154-4576-8f92-e22310e8e1f2.png)

**Comment by mpage21** [comment]
Additionally, it seems that when I use the flip = TRUE param, the numbers don't display correctly (they aren't level)

**Comment by mcneney** [comment]
Hi, thanks for your interest in LDheatmap. You need to edit the grob that holds the text. Try something like

```
LDheatmap(test_matrix, color = rgb.palette(18), text=TRUE,name="myld") # name LDheatmap grop "myld"
grid::grid.edit(gPath("myld","heatMap","heatmaptext"),gp=gpar(cex=1.5))
```

The text orientation when the heatmap is flipped was the easiest to implement. At some point we'll revamp the flipped heatmap code and will take your comment into account.

Brad

**Comment by mpage21** [comment]
Thank you for this, I was able to increase the text size.
